name: saber_landing
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  http: ^1.4.0
  jaspr: ^0.21.7
  jaspr_content: ^0.4.4
  jaspr_router: ^0.8.0
  universal_web: ^1.1.0+2

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.5+1
  jaspr_builder: ^0.21.6
  jaspr_lints: ^0.5.1
  lints: ^6.0.0

jaspr:
  mode: static
